---
- name: Pull and Run docker image of nayan16/devopscalc
  hosts: all
  tasks:
    - name: Pull rishabhtyagi22/calculator
      docker_image:
        name: rishabhtyagi22/calculator
        source: pull
  
